package com.collectx.strategy.dto;

import lombok.Data;

/**
 * DTO for creating a Strategy Rule (ADMIN only).
 * ruleId is NOT included — auto-generated by the DB (@GeneratedValue IDENTITY).
 */
@Data
public class RuleRequestDTO {
    // ruleId intentionally omitted — DB auto-assigns it
    private String name;
    private String bucket;    // "0-30" / "31-60" / "61-90" / "90+"
    private String riskBand;  // LOW / MED / HIGH
    private Integer priority;
}
